#port
server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webinar-admin?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

# log4j2
logging:
  config: classpath:log4j2.xml
knife4j:
  enable: true

